// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/layoutBase/components/header/components/Avatar.vue')['default']
    BreadCrumb: typeof import('./src/components/layoutBase/components/header/components/BreadCrumb.vue')['default']
    ChangeLanguage: typeof import('./src/components/changeLanguage/ChangeLanguage.vue')['default']
    Content: typeof import('./src/components/layoutBase/components/content/Content.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/layoutBase/components/header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/icon/Icon.vue')['default']
    Info: typeof import('./src/components/layoutBase/components/header/components/Info.vue')['default']
    LayoutBase: typeof import('./src/components/layoutBase/index.vue')['default']
    Screenfull: typeof import('./src/components/layoutBase/components/header/components/Screenfull.vue')['default']
    Setting: typeof import('./src/components/layoutBase/components/header/components/Setting.vue')['default']
    Sidebar: typeof import('./src/components/layoutBase/components/sidebar/Sidebar.vue')['default']
  }
}

export { }
