// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./../components/layoutBase/header/components/Avatar.vue')['default']
    BreadCrumb: typeof import('./../components/layoutBase/header/components/BreadCrumb.vue')['default']
    ChangeLanguage: typeof import('./../components/changeLanguage/index.vue')['default']
    Content: typeof import('./../components/layoutBase/content/Content.vue')['default']
    Header: typeof import('./../components/layoutBase/header/Header.vue')['default']
    Info: typeof import('./../components/layoutBase/header/components/Info.vue')['default']
    LayoutBase: typeof import('./../components/layoutBase/index.vue')['default']
    LayoutOpen: typeof import('./../components/layoutOpen/index.vue')['default']
    LayoutQuery: typeof import('./../components/layoutQuery/index.vue')['default']
    MoreButton: typeof import('./../components/layoutBase/tabs/components/MoreButton.vue')['default']
    MyDialog: typeof import('./../components/myDialog/index.vue')['default']
    MyDraggable: typeof import('./../components/myDraggable/index.vue')['default']
    MyIcon: typeof import('./../components/myIcon/index.vue')['default']
    MyMap: typeof import('./../components/myMap/index.vue')['default']
    MyTable: typeof import('./../components/myTable/index.vue')['default']
    MyTextEditor: typeof import('./../components/myTextEditor/index.vue')['default']
    Screenfull: typeof import('./../components/layoutBase/header/components/Screenfull.vue')['default']
    Select: typeof import('./../components/layoutBase/header/components/Select.vue')['default']
    Setting: typeof import('./../components/layoutBase/header/components/Setting.vue')['default']
    Sidebar: typeof import('./../components/layoutBase/sidebar/Sidebar.vue')['default']
    Tabs: typeof import('./../components/layoutBase/tabs/index.vue')['default']
    TreeMenu: typeof import('./../components/layoutBase/sidebar/components/TreeMenu.vue')['default']
  }
}

export { }
